### PR TITLE
Fixes #119 - workaround for Intel 2021 bug.

### LINKED ISSUE #119: Fail with Intel 2021
This is a compiler defect, but the workaround is trivial.    Replaces ASSOCIATE block with wordier version of one statement.

### PR DESCRIPTION
**Pull request by tclune**

### CODE REVIEW

**Review by WilliamJamieson — COMMENTED** [review]
Looks good!

**Review by WilliamJamieson — APPROVED** [review]

**Comment by tclune** [comment]
Don't know why the CI tests are failing.  They work manually on my system.

**Comment by ZedThree** [comment]
Sorry, this is my fault -- checking out `cmake-fixes` in `tools/travis-install-gfe.sh` should fix things:

```
#!/bin/bash

set -e

GFE_DIR=${HOME}/gfe
mkdir -p ${GFE_DIR}

# First install prerequisites
GFE_INSTALL_DIR=${HOME}/Software/GFE
mkdir -p ${GFE_INSTALL_DIR}

to_build=(pFUnit)
for repo in "${to_build[@]}"
do
   cd ${GFE_DIR}
   git clone https://github.com/Goddard-Fortran-Ecosystem/${repo}.git
   cd ${GFE_DIR}/${repo}
   # Necessary for consistent CMake targets
   git checkout cmake-fixes
   mkdir build && cd build
   cmake .. -DCMAKE_INSTALL_PREFIX=${GFE_INSTALL_DIR} -DCMAKE_PREFIX_PATH=${GFE_INSTALL_DIR}
   make -j$(nproc) install
done
```

**Comment by tclune** [comment]
Can you do a PR (hotfix) for that?

**Comment by mathomp4** [comment]
Eeeeee. That is scary. That means we will *ALWAYS* need a `cmake-fixes` branch in pFUnit.

**Comment by ZedThree** [comment]
@mathomp4 That change can be reverted when the [`cmake-fixes` PR is merged](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/pull/273)

The Intel test on the pFUnit PR is failing because it needs the change in this PR

**Pull request merged**
