### PR TITLE
add non-type bound procedures

### PR DESCRIPTION
**Pull request by weiyuan-jiang**

### CODE REVIEW

**Comment by weiyuan-jiang** [comment]
@tclune , please take a look.  It has not been  tested

**Comment by tclune** [comment]
This looks right.

1. Have you double checked:  deque, queue, and stack containers to be sure that they have the required interfaces.  (Need to consult STL standard - as they don't have iterators which makes them different.)
2. Bonus points if you could add a few unit tests that exercise these.   Nothing fancy  just make sure that they work in a real bit of code so that we don't "test" with GEOS.   Possibly I did this in Vector already and you can again just cut/paste/modify for map and ordered_map.

**Comment by weiyuan-jiang** [comment]
> 

Ok, please teach me how to run the tests.  I can add Map test

**Comment by tclune** [comment]
CI will run the existing tests for you.   But basically you need to first build pFUnit.  The way I usually do this cleanly is create a directory that will contain all of the GFE repos.    ANd then set an env variable "GFE" to be the install path that they all share.

You then build each repo in the order [gFTL, gFTL-shared, fArgParse, pFUnit]:
```
1. cd <repo>
2. mkdir build
3. cd build
4. cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$GFE -DCMAKE_PREFIX_PATH=$GFE
5. make install
```
You then go back to gFTL a second time.  When you do the cmake this time, it will "find" pFUnit, and you can then just do:
`make tests`

**Review by tclune — APPROVED** [review]

**Pull request merged**
